profile_page:
    path:   /profile/
    defaults: { _controller: testBundle:Default:show}
test_add:
    path:   /profile/edituser
    defaults: { _controller: testBundle:Default:new}
feed_home:
    path:   /
    defaults: { _controller: testBundle:Default:showStatus}
