testBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
    
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
        picture:
            type: string
            length: 255
        fosuserid:
            type: integer
            legth: 11
